/***************************************************************
 * THIS FILE IS AUTOGENERATED!!
 * use command 'npm run compile' to export files
***************************************************************/

export * from './useGetUserTest';