const PRIMARY_COLOR = '#1E2F4E'
const SECONDARY_COLOR = '#596171'
const BACKGROUND_COLOR = '#F6F7FA'
const SUCCESS_BLUE = '#005AFF'
const ALERT_COLOR = '#FF2400'
const WHITE = '#FFFFFF'
const WHITE_WHITE = '#FFFFFF'
const BLACK = '#000000'
const GRAY = '#605C5C'
const LIGHT_GRAY = '#D9D9D9'
const SUBTITLE_GRAY = '#748199'
const BLACK_GRADIENT = ['transparent', 'rgba(0, 0, 0, 0.78)']
const CARD_BOARDER_COLOR = '#e4e5ea'
const TRANSPARENT = 'transparent'
const LOADING_GRADIENT = ['#E4E5EA', '#F4F5FA', '#E4E5EA']

export const COLORS = {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  BACKGROUND_COLOR,
  ALERT_COLOR,
  SUBTITLE_GRAY,
  WHITE,
  WHITE_WHITE,
  BLACK,
  GRAY,
  LIGHT_GRAY,
  BLACK_GRADIENT,
  CARD_BOARDER_COLOR,
  SUCCESS_BLUE,
  TRANSPARENT,
  LOADING_GRADIENT,
}
