const PRIMARY_COLOR = '#1E2F4E'
const SECONDARY_COLOR = '#92A3C1'
const BACKGROUND_COLOR = '#005AFF'
const SUCCESS_BLUE = '#5588E6'
const ALERT_COLOR = '#FF2400'
const WHITE = '#F8F9FB'
const WHITE_WHITE = '#FFFFFF'
const BLACK = '#000000'
const GRAY = '#605C5C'
const LIGHT_GRAY = '#D9D9D9'
const SUBTITLE_GRAY = '#748199'
const BLACK_GRADIENT =  ['transparent', 'rgba(0, 0, 0, 0.78)']
const CARD_BOARDER_COLOR = 'rgba(52, 52, 52, .1)'

export const COLORS = {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  BACKGROUND_COLOR,
  ALERT_COLOR,
  SUBTITLE_GRAY,
  WHITE,
  WHITE_WHITE,
  BLACK,
  GRAY,
  LIGHT_GRAY,
  BLACK_GRADIENT,
  CARD_BOARDER_COLOR,
  SUCCESS_BLUE
}
