const SPACING_NONE = 0
const SPACING_NUDGE_XS = 1
const SPACING_NUDGE_S = 2

const SPACING_XS_4 = 4
const SPACING_XS_8 = 8
const SPACING_XS_12 = 12
const SPACING_XS_16 = 16

const SPACING_S_20 = 20
const SPACING_S_24 = 24
const SPACING_S_28 = 28
const SPACING_S_32 = 32

const SPACING_MD_36 = 36
const SPACING_MD_40 = 40
const SPACING_MD_48 = 48
const SPACING_MD_52 = 52

const SPACING_LG_56 = 56
const SPACING_LG_60 = 60
const SPACING_LG_64 = 64
const SPACING_LG_68 = 68

const SPACING_XL_72 = 72
const SPACING_XL_76 = 76
const SPACING_XL_80 = 80
const SPACING_XL_88 = 88

const FLEX_ROW = 'row'
const FLEX_START = 'flex-start'
const FLEX_COLUMN = 'column'
const ALIGN_CENTER = 'center'
const POSITION_ABSOLUTE = 'absolute'
const SPACE_BETWEEN = 'space-between'
const DISPLAY_NONE = 'none'
const OVERFLOW_HIDDEN = 'hidden'

export const LAYOUT = {
  SPACING_NONE,
  SPACING_NUDGE_XS,
  SPACING_NUDGE_S,
  SPACING_XS_4,
  SPACING_XS_8,
  SPACING_XS_12,
  SPACING_XS_16,
  SPACING_S_20,
  SPACING_S_24,
  SPACING_S_28,
  SPACING_S_32,
  SPACING_MD_36,
  SPACING_MD_40,
  SPACING_MD_48,
  SPACING_MD_52,
  SPACING_LG_56,
  SPACING_LG_60,
  SPACING_LG_64,
  SPACING_LG_68,
  SPACING_XL_72,
  SPACING_XL_76,
  SPACING_XL_80,
  SPACING_XL_88,
  FLEX_ROW,
  FLEX_COLUMN,
  FLEX_START,
  ALIGN_CENTER,
  POSITION_ABSOLUTE,
  SPACE_BETWEEN,
  DISPLAY_NONE,
  OVERFLOW_HIDDEN,
}
