const fs = require('fs')
const path = require('path')
const glob = require('glob')

const directoryPattern = './app/lib/**/hooks' // Specify the directory pattern using glob syntax

// Find directories matching the directory pattern recursively
const directories = glob.sync(directoryPattern, { onlyDirectories: true })

directories.forEach(directory => {
  const indexPath = path.join(directory, 'index.js') // Path to the index.js file in the current directory

  // Find files in the current directory
  const files = glob.sync(path.join(directory, '*.js'))

  const exportStatements = []

  // Iterate over the files
  files.forEach(file => {
    // Skip the index.js file
    if (file === indexPath) {
      return
    }

    const fileName = path.basename(file, '.js') // Extract the file name without the extension
    const exportStatement = `export * from './${fileName}'` // Create the export statement
    exportStatements.push(exportStatement)
  })

  // Generate the content of the index.js file
  const indexContent = `/***************************************************************
 * THIS FILE IS AUTOGENERATED!!
 * use command 'npm run compile' to export files
 ***************************************************************/\n\n${exportStatements.join(
   '\n',
 )}\n`

  // Write the content to the index.js file, overwriting any existing file
  fs.writeFileSync(indexPath, indexContent)
})

console.log('New index.js files generated successfully.')
